In [3]:
#### All numpy functions

In [2]:
# import numpy

# !pip install numpy

import numpy as np


In [3]:

all_functions = [i for i in dir(np) if not '_' in (i[:2] or i[1]) and i[:1].isupper() == False]

print(f"numpy all functions count : {len(all_functions)}")

for i, v in enumerate(all_functions):
    print(f"{i} : {v}")


numpy all functions count : 526
0 : abs
1 : absolute
2 : add
3 : add_docstring
4 : add_newdoc
5 : add_newdoc_ufunc
6 : all
7 : allclose
8 : alltrue
9 : amax
10 : amin
11 : angle
12 : any
13 : append
14 : apply_along_axis
15 : apply_over_axes
16 : arange
17 : arccos
18 : arccosh
19 : arcsin
20 : arcsinh
21 : arctan
22 : arctan2
23 : arctanh
24 : argmax
25 : argmin
26 : argpartition
27 : argsort
28 : argwhere
29 : around
30 : array
31 : array2string
32 : array_equal
33 : array_equiv
34 : array_repr
35 : array_split
36 : array_str
37 : asanyarray
38 : asarray
39 : asarray_chkfinite
40 : ascontiguousarray
41 : asfarray
42 : asfortranarray
43 : asmatrix
44 : atleast_1d
45 : atleast_2d
46 : atleast_3d
47 : average
48 : bartlett
49 : base_repr
50 : binary_repr
51 : bincount
52 : bitwise_and
53 : bitwise_not
54 : bitwise_or
55 : bitwise_xor
56 : blackman
57 : block
58 : bmat
59 : bool8
60 : bool_
61 : broadcast
62 : broadcast_arrays
63 : broadcast_shapes
64 : broadcast_to
65 : busday_count
66 

## start coding

In [4]:
#first function is np.abs

array = np.array([-1, -2, -3, -4, -5])
np.absolute(array) # or np.abs(array)


array([1, 2, 3, 4, 5])

In [5]:

#second function is np.add

a1 = 123
a2 = 321
np.add(a1, a2)

array1 = np.array([0,1,2,3,4,5,6,7,8]).reshape(3,3)
array2 = np.array([0,1,2])

np.add(array1, array2)


array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [6]:

#third function is np.add_docstring

def func():
    # """
    # you need write doc string here
    # """
    return "there is not any documentation string. please add documentation string"

np.add_docstring(func, "this is documentation string")

print(func.__doc__)


this is documentation string


In [7]:

# fourth function is np.add_newdoc

#create example.py and write in it the code
                                            # class New:
                                            #     def __init__(self, a):
                                            #         self.a = a
                                            #
                                            #     def main(self):
                                            #         return "docs iqrorjon"


#and write in main.py the codes
import example
np.add_newdoc('example', 'New', "this is a new docstring")
print(example.New.__doc__)



this is a new docstring


/var/folders/7v/1c76ypv54yx261vygq63_47w0000gp/T/ipykernel_5396/125474528.py:14: UserWarning: add_newdoc was used on a pure-python object <class 'example.New'>. Prefer to attach it directly to the source.
  np.add_newdoc('example', 'New', "this is a new docstring")


In [322]:

# fifth function is np.add_newdoc_ufunc
np.add_newdoc_ufunc(np.multiply, "this is a new string")
print(np.multiply.__doc__)


In [9]:

#sixth function is np.all

array1 = np.array([[True, False],
                   [True, True]])
print(np.all(array1))
print(np.all(array1, axis=1)) # axis=1 is horizontal

False
[False  True]


In [10]:

#seventh function is np.allclose

print(np.allclose([1.0, -2.0], [1.0, -2.0]))

print(np.allclose([2.0, 3.0], [3.0, 2.0]))


True
False


In [11]:

# eighth function is np.alltrue

array1 = np.array([True,1,2,3,4,5])
array2 = np.array([False,1,2,3,4,5])

print(np.alltrue(array1))
print(np.alltrue(array2))


True
False


In [12]:

# ninth function is np.amax

array = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

print(np.amax(array))
print(np.amax(array, axis=0))
print(np.amax(array, axis=1))


9
[7 8 9]
[3 6 9]


In [13]:

# tenth function is np.amin

array = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

print(np.amin(array))
print(np.amin(array, axis=0))
print(np.amin(array, axis=1))


1
[1 2 3]
[1 4 7]


In [14]:
# eleventh function is np.angle

np.angle([1.0, 1.0j, 1+1j])


array([0.        , 1.57079633, 0.78539816])

In [15]:

# twelfth function is np.any

array1 = np.array([False, False, False])
array2 = np.array([True, False, False])

print(np.any(array1))
print(np.any(array2))


False
True


In [16]:

# thirteenth function is np.append

array = np.array([[1,2,3],
                  [4,5,6]])

np.append(array, [[7,8,9]], axis=0)



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:

# fourteenth function is np.apply_along_axis

def func(arr):
    return arr[0] * 10

array = np.array([[1,2,3],
                  [4,5,6]])

np.apply_along_axis(func, 1, array)


array([10, 40])

In [18]:

# fifteenth function is np.apply_over_axes

def func(arr, axis):
    return arr[axis]*10

array = np.array([[[1,2],
                   [3,4]],
                  [[5,6],
                   [7,8]]])

np.apply_over_axes(func, array, [1, 1])


array([[[700, 800]]])

In [22]:

# sixteenth function is np.arange
array = np.arange(start=1, stop=10, step=1, dtype='float')
array


array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [27]:

#seventeenth function is np.arccos

np.arccos([1,-1,0])


array([0.        , 3.14159265, 1.57079633])

In [30]:

#eighteenth function is np.arccosh

np.arccosh([4,2,3])


array([2.06343707, 1.3169579 , 1.76274717])

In [38]:

#nineteenth function is np.arcsin

np.arcsin([-1, 0, 1])


array([-1.57079633,  0.        ,  1.57079633])

In [39]:

#twentieth function is np.arcsinh
np.arcsinh([1,2,3])


array([0.88137359, 1.44363548, 1.81844646])

In [40]:

#twenty first function is np.arctan

np.arctan([1,2,3])


array([0.78539816, 1.10714872, 1.24904577])

In [43]:

#twenty second function is np.arctan2

array1 = np.array([1,2,-1])
array2 = np.array([-1,-2,1])
np.arctan2(array1, array2)


array([ 2.35619449,  2.35619449, -0.78539816])

In [48]:

#twenty third function is np.arctanh

np.arctanh([0.1, -0.6])


array([ 0.10033535, -0.69314718])

In [55]:

#twenty fourth function is np.argmax

array = np.arange(10).reshape(5,2)*11

print(array)
np.argmax(array, axis=0)


[[ 0 11]
 [22 33]
 [44 55]
 [66 77]
 [88 99]]


array([4, 4])

In [63]:

#twenty fifth function is np.argmin

array = np.arange(1, 11).reshape(5,2)*10
print(array)
np.argmin(array, axis=0)

[[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]]


array([0, 0])

In [79]:

#twenty sixth function is np.argpartition
array = np.array([-1,1,2,3,4,5])

print(np.argpartition(array, 1))
print(np.argpartition(array, 5))


[0 1 2 3 4 5]
[1 0 2 3 4 5]


In [112]:

#twenty seventh function is np.argsort

array = np.array([3,4,2,1,0])
print(array[np.argsort(array)])

array1 = np.array([[3,2,5],
                   [6,1,0],
                   [5,8,1]])

sorted_arr_index = np.argsort(array1, axis=1)
print(sorted_arr_index)


[0 1 2 3 4]
[[1 0 2]
 [2 1 0]
 [2 0 1]]


In [158]:

#twenty eighth function is np.argwhere

array = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

np.argwhere(array==5).flatten()


array([1, 1])

In [161]:

#twenty nineth function is np.around

array = np.array([1.82345, 3.42325, 5.24642])

np.round(array, decimals=2)


array([1.82, 3.42, 5.25])

In [162]:

#thirty function is np.array

array = np.array([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

In [192]:

#thirty first function is np.array2string

array = np.arange(100)
np.array2string(array, separator=' \n ')


'[ 0 \n  1 \n  2 \n  3 \n  4 \n  5 \n  6 \n  7 \n  8 \n  9 \n 10 \n 11 \n 12 \n 13 \n 14\n 15 \n 16 \n 17 \n 18 \n 19 \n 20 \n 21 \n 22 \n 23 \n 24 \n 25 \n 26 \n 27 \n 28 \n 29\n 30 \n 31 \n 32 \n 33 \n 34 \n 35 \n 36 \n 37 \n 38 \n 39 \n 40 \n 41 \n 42 \n 43 \n 44\n 45 \n 46 \n 47 \n 48 \n 49 \n 50 \n 51 \n 52 \n 53 \n 54 \n 55 \n 56 \n 57 \n 58 \n 59\n 60 \n 61 \n 62 \n 63 \n 64 \n 65 \n 66 \n 67 \n 68 \n 69 \n 70 \n 71 \n 72 \n 73 \n 74\n 75 \n 76 \n 77 \n 78 \n 79 \n 80 \n 81 \n 82 \n 83 \n 84 \n 85 \n 86 \n 87 \n 88 \n 89\n 90 \n 91 \n 92 \n 93 \n 94 \n 95 \n 96 \n 97 \n 98 \n 99]'

In [193]:

#thirty second function is np.array_equal

array1 = np.array([1,2,-1])
array2 = np.array([1,2,-1])

np.array_equal(array1, array2)


True

In [197]:

#thirty third function is np.array_equiv

print(np.array_equiv([1,2,-4], [1,2,-4]))
print(np.array_equiv([1,2,-4], [[1,2,-4]]))

True
True


In [198]:

#thirty fourth function is np.array_repr

array = np.array([1,2,3,-1,-1j])

np.array_repr(array)


'array([ 1.+0.j,  2.+0.j,  3.+0.j, -1.+0.j, -0.-1.j])'

In [203]:

#thirty fifth function is np.array_split

array = np.arange(1, 6)

np.array_split(array, 3)


[array([1, 2]), array([3, 4]), array([5])]

In [209]:

#thirty sixth function is np.array_str

array = np.array([-1,2,3,-4])

np.array_str(array)


'[-1  2  3 -4]'

In [212]:

#thirty seventh function is np.asanyarray

array = [1,2,3,4,45]

print(type(np.asanyarray(array)))
np.asanyarray(array)


<class 'numpy.ndarray'>


array([ 1,  2,  3,  4, 45])

In [234]:

#thirty eighth function is np.asarray

array2 = [1,2,3]
np.asarray(array2)

array([1, 2, 3])

In [249]:

#thirty nineth function is np.asarray_chkfinite

array = [1,2,np.inf]

try:
    print(np.asarray_chkfinite(array))
except:
    print('it has inf number or numpy nan')
    print("ValueError")


it has inf number or numpy nan
ValueError


In [251]:

#fourty function is np.ascontiguousarray

array = [1,2,3,4]

array = np.ascontiguousarray(array)
array.flags


  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [253]:

#fourty first function is np.asfarray

array = [1,2,3,4,5]
print(np.asfarray(array))
print(np.asfarray(array).dtype)


[1. 2. 3. 4. 5.]
float64


In [254]:

#fourty second function is np.asfortranarray

array = [1,2,3,4,5]

print(np.asfortranarray(array))
print(np.asfortranarray(array).flags)


[1 2 3 4 5]
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [262]:

#fourty third function is np.asmatrix

array = np.array([[1,2,3],
                  [5,6,7]])

array2 = np.asmatrix(array)
array2


matrix([[1, 2, 3],
        [5, 6, 7]])

In [266]:

#fourty fourth function is np.atleast_1d

array = np.array([1.0, 2.0, 3.0])
np.atleast_1d(array)


array([[1., 2., 3.]])

In [268]:

#fourty fifth function is np.atleast_2d
np.atleast_2d(1.0, 2.0, 3.0)


[array([[1.]]), array([[2.]]), array([[3.]])]

In [270]:

#fourty sixth function is np.atleast_3d

print(np.atleast_3d(11))
print(np.atleast_3d(1,2,3))

[[[11]]]
[array([[[1]]]), array([[[2]]]), array([[[3]]])]


In [276]:

#fourty seventh function is np.average

array1 = np.arange(1, 16).reshape(3,5)
print(array1)
print(np.average(array1, axis=1))


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[ 3.  8. 13.]


In [283]:

#fourty eighth function is np.bartlett

print(np.bartlett(10))
print(np.bartlett(10).round(2)*100)


[0.         0.22222222 0.44444444 0.66666667 0.88888889 0.88888889
 0.66666667 0.44444444 0.22222222 0.        ]
[ 0. 22. 44. 67. 89. 89. 67. 44. 22.  0.]


In [290]:

#fourty nineth function is np.base_repr
for i in range(10):
    print(np.base_repr(i))


0
1
10
11
100
101
110
111
1000
1001


In [308]:

#fifty function is np.binary_repr

for i in range(10):
    print(np.binary_repr(i, width=2))


00
01
10
11
100
101
110
111
1000
1001


/var/folders/7v/1c76ypv54yx261vygq63_47w0000gp/T/ipykernel_5396/2130556825.py:4: DeprecationWarning: Insufficient bit width provided. This behavior will raise an error in the future.
  print(np.binary_repr(i, width=2))


In [318]:

#fifty first function is np.bincount
array = np.array([1,2,3,4,1])
print(np.bincount(array))


[0 2 1 1 1]
